version: '3.3'
services:  
  conexcion:
    image: nginx:latest
    volumes:
    - C:\Users\JoaquinGA\Desktop\SaludosDividido\proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8080:80    
    networks:
      - mired
    environment:
      MYSQL_HOST: db
    depends_on:
      - db
    links:
      - db
    restart: always 
    
  db:
    image: mariadb
    networks:
      - mired
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - C:\Users\JoaquinGA\Downloads\Docker\saludosdivididos\SaludosDividido\script.sql:/docker-entrypoint-initdb.d/bd.sql
      #- C:\Users\JoaquinGA\Downloads\Docker\saludosdivididos\SaludosDividido\datos:/var/lib/mysql  
    
networks:
  mired: